name: PlotMe
main: com.worldcretornica.plotme.PlotMe
version: 0.5
author: ZachBora
load: startup
website: http://dev.bukkit.org/server-mods/plotme/
loadbefore: [bPermissions]
softdepend: [WorldEdit]
description: >
             Handles plot creation, management and protection
commands:
  plotme:
    description: List plotme commands
    usage: /plotme
    aliases: [p, plot]