name: PlotMe
main: com.worldcretornica.plotme.PlotMe
version: 0.6c
author: ZachBora
load: startup
website: http://dev.bukkit.org/server-mods/plotme/
loadbefore: [bPermissions]
softdepend: [WorldEdit]
description: >
             Handles plot creation, management and protection
commands:
  plotme:
    description: List plotme commands
    usage: /plotme
    aliases: [p, plot]
    
permissions:
  plotme.use:
    description: Gives default user commands
    children:
      plotme.use.claim: true
      plotme.use.auto: true
      plotme.use.home: true
      plotme.use.info: true
      plotme.use.comment: true
      plotme.use.comments: true
      plotme.use.biome: true
      plotme.use.clear: true
      plotme.use.list: true
  plotme.use.claim:
    description: Gives the claim command
  plotme.use.auto:
    description: Give the auto command
  plotme.use.home:
    description: Give the home command
  plotme.use.info:
    description: Give the info command
  plotme.use.comment:
    description: Give the comment command
  plotme.use.comments:
    description: Give the comments command
  plotme.use.biome:
    description: Give the biome and biomelist command
  plotme.use.clear:
    description: Give the clear command for plots owned
  plotme.use.list:
    description: Give the list command
  plotme.use.add:
    description: Give the add command for plots owned
  plotme.use.remove:
    description: Give the remove command for plots owned
  plotme.limit.*:
    description: Give unlimited plots
  plotme.admin:
    description: Give default admin commands 